// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:manga_base/data/book.dart';
import 'package:manga_base/data/user.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(BookAdapter());
    registerAdapter(UserAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(BookAdapter());
    registerAdapter(UserAdapter());
  }
}
